# Travis config for loopfusion

language: c

cache: ccache

matrix:
  include:
    # Build and test against the master (stable) and devel branches of Nim
    # Build and test using both gcc and clang
    - os: linux
      env: CHANNEL=stable
      compiler: gcc

    - os: linux
      env: CHANNEL=devel
      compiler: gcc

    # On OSX we only test against clang (gcc is mapped to clang by default)
    - os: osx
      env: CHANNEL=stable
      compiler: clang

  allow_failures:
    # Ignore failures when building against the devel Nim branch
    # Also ignore OSX, due to very long build time and random homebrew errors
    - env: CHANNEL=devel
    - os: osx
  fast_finish: true

# # ubuntu 14;04 dependency (Travis is still 14.04)
# addons:
#   apt:
#     packages:
#       - libyourdependency-dev

# # macOS dependencies
# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yourdependency; fi

install:
  - export CHOOSENIM_NO_ANALYTICS=1
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=~/.nimble/bin:$PATH
  - echo "export PATH=~/.nimble/bin:$PATH" >> ~/.profile
  - choosenim $CHANNEL

script:
    - nimble refresh
    - nimble test

branches:
  except:
    - gh-pages
